remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme

title: PancreAmigos
description: Projeto Mobile para a matéria Métodos de Desenvolvimento de Software da Universidade de Brasília.