[book]
authors = ["Liander Medeiros Alves", 
            "Pedro Miguel Martins De Oliveira Dos Santos",
            "Igor Alves De Abreu",
            "Marcos Paulo Amorim Ribeiro",
            "Felipe Guimaraes Fernandes"]
language = "pt-br"
multilingual = false
src = "src"
title = "PancreAmigo"

[build]
build-dir = "book"
create-missing = true

[output.html]
#theme = ""
default-theme = "light"
preferred-dark-theme = "ayu"
curly-quotes = true
mathjax-support = false
#additional-css = ["custom.css"]
#additional-js = ["custom.js"]
no-section-label = true
git-repository-url = "https://github.com/mdsreq-fga-unb/2023.1-PancreAmigo/"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/mdsreq-fga-unb/2023.1-PancreAmigo/edit/gh-pages/{path}"
#site-url = "/"
cname = "pancreamigo.com.br"
#input-404 = "not-found.md"

[output.html.fold]
enable = true
