name: Android Release

on:
  push:
    branches: [ "master" ]
    
  workflow_dispatch:

jobs:

  version:
    name: Create version number
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.10.2
        with:
          versionSpec: "5.x"
      - name: Use GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.10.2

      - name: Create version.txt with nuGetVersion
        run: echo ${{ steps.gitversion.outputs.nuGetVersion  }} > version.txt

      - name: Upload version.txt
        uses: actions/upload-artifact@v2
        with:
          name: gitversion
          path: version.txt

  build:
    name: Create Android Build

    needs: version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
  
      - name: Get version.txt
        uses: actions/download-artifact@v2
        with:
          name: gitversion

      - name: Create new file without newline char from version.txt
        run: tr -d '\n' < version.txt > version1.txt

      - name: Read version
        id: version
        uses: juliangruber/read-file-action@v1
        with:
          path: version1.txt

      - name: Update version in YAML
        run: sed -i 's/99.99.99+99/${{ steps.version.outputs.content }}+${{ github.run_number }}/g' pancreamigo/pubspec.yaml

      - name: Download Android keystore
        id: android_keystore
        uses: timheuer/base64-to-file@v1.0.3
        with:
          fileName: upload-keystore.jks
          encodedString: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}

      - name: Create key.properties
        run: |
          echo "storeFile=${{ steps.android_keystore.outputs.filePath }}" > pancreamigo/android/key.properties
          echo "storePassword=${{ secrets.PLAY_STORE_KEYSTORE_PASSWORD }}" >> pancreamigo/android/key.properties
          echo "keyPassword=${{ secrets.PLAY_STORE_KEY_PASSWORD }}" >> pancreamigo/android/key.properties
          echo "keyAlias=${{ secrets.PLAY_STORE_KEY_ALIAS }}" >> pancreamigo/android/key.properties
      
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "12.x"
          cache: gradle

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.7.12"
          channel: 'stable'
          cache: true
        
      - name: Get dependencies
        run: |
              cd pancreamigo
              flutter pub get

      - name: Start Android Release Build
        run: |
              cd pancreamigo
              flutter build appbundle

      - name: Upload Android Release
        uses: actions/upload-artifact@v2
        with:
          name: android-release
          path: pancreamigo/build/app/outputs/bundle/release/app-release.aab


  deploy:
    name: Deploy Android Build
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Get Android Build from artifacts
        uses: actions/download-artifact@v2
        with:
          name: android-release

      - name: Release Build to internal track
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.PLAYSTORE_ACCOUNT_KEY }}
          packageName: com.pancreamigo
          releaseFiles: app-release.aab
          track: alpha
          status: completed
